package bankingOperationsApp;

/**
* bankingOperationsApp/BankingOperationsHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from BankingOperations
* Tuesday, November 21, 2017 1:53:47 o'clock AM EST
*/

public final class BankingOperationsHolder implements org.omg.CORBA.portable.Streamable
{
  public bankingOperationsApp.BankingOperations value = null;

  public BankingOperationsHolder ()
  {
  }

  public BankingOperationsHolder (bankingOperationsApp.BankingOperations initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = bankingOperationsApp.BankingOperationsHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    bankingOperationsApp.BankingOperationsHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return bankingOperationsApp.BankingOperationsHelper.type ();
  }

}
