package bankingOperationsApp;


/**
* bankingOperationsApp/BankingOperationsOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from BankingOperations
* Tuesday, November 21, 2017 1:53:47 o'clock AM EST
*/

public interface BankingOperationsOperations 
{
  boolean createAccountRecord (String firstName, String lastName, String address, String phone, String branch);
  boolean editRecord (String customerID, String fieldName, String newValue);
  String[] getAccountCount ();

  //new method
  boolean transferFund (String managerID, double amount, String sourceCustomerID, String destinationCustomerID);

  //Customer specific methods
  boolean deposit (String customerID, double amt);
  boolean withdraw (String customerID, double amt);
  double getBalance (String customerID);
} // interface BankingOperationsOperations
