package bankingOperationsApp;


/**
* bankingOperationsApp/custCountHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from BankingOperations
* Tuesday, November 21, 2017 1:53:47 o'clock AM EST
*/

public final class custCountHolder implements org.omg.CORBA.portable.Streamable
{
  public String value[] = null;

  public custCountHolder ()
  {
  }

  public custCountHolder (String[] initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = bankingOperationsApp.custCountHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    bankingOperationsApp.custCountHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return bankingOperationsApp.custCountHelper.type ();
  }

}
